# Generated by Django 3.1 on 2020-10-02 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holamundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigoCarrera',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='carrera',
            name='nombreCarrera',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='carrera',
            name='numeroCiclo',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='carrera',
            name='numeroCreditos',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='carrera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='holamundo.carrera'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='ciclo',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='nombre',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
