# Generated by Django 3.1 on 2020-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holamundo', '0002_auto_20201002_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Edad', models.IntegerField(default=5)),
                ('Telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('Ocupaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
